# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on: push

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version:
          - 3.10.11
          - 3.11
          - 3.12
    steps:
    - uses: actions/checkout@v4
    - name: Setup rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
        version: '0.39.0'
    - name: Pin Python version
      run: rye pin ${{ matrix.python-version }}
    - name: Setup environment
      run: make .venv
    - name: Test with pytest
      run: make coverage.xml
    - name: Check formatting
      run: rye fmt --check parafac2
    - name: Check linting
      run: rye lint parafac2
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true